version: '3'

services:
  nodejs:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ../mvd:/mvd
    environment:
      - SERVER_PORT=8000
      - USERNAME=root
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5