name: Node Github CI

on:
  push:
    branches:
      - addDocker

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: npm install and test
        run: |
          npm install
          node server.js
          exit
