name: Node Github CI

on:
  push:
    branches:
      - addDocker

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker ps
        run: docker-compose ps

      - name: docker down
        run: docker-compose down

      - name: docker run
        run: docker-compose up -d

      - name: docker logs
        run: sleep 10 && docker-compose logs

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: nodeLogs
          retention-days: 5
